// Desktop-only services (audio playback, USB export/sync, file import/analysis, device
// detection, media keys, diagnostics) are gated behind the `desktop` feature so the mobile
// build excludes them and their heavy native dependencies.
#[cfg(feature = "desktop")]
pub mod analysis;
pub mod artwork;
#[cfg(feature = "desktop")]
pub mod audio;
pub mod backup;
pub mod cloud_sync;
pub mod collection;
#[cfg(feature = "desktop")]
pub mod device;
#[cfg(feature = "desktop")]
pub mod device_sync;
#[cfg(feature = "desktop")]
pub mod diagnostics;
pub mod discovery;
#[cfg(feature = "desktop")]
pub mod export;
pub mod follow;
#[cfg(feature = "desktop")]
pub mod hash;
#[cfg(target_os = "ios")]
pub mod ios_splash;
#[cfg(feature = "desktop")]
pub mod library;
pub mod media_controls;
pub mod playlist;
pub mod settings;
pub mod smart_rules;
pub mod tag;
pub mod ui_zoom;
pub mod watch_gate;

#[cfg(feature = "desktop")]
pub use analysis::AnalysisService;
pub use artwork::ArtworkService;
#[cfg(feature = "desktop")]
pub use audio::AudioService;
pub use backup::BackupService;
pub use collection::CollectionService;
#[cfg(feature = "desktop")]
pub use device::DeviceService;
#[cfg(feature = "desktop")]
pub use device_sync::SyncService;
#[cfg(feature = "desktop")]
pub use diagnostics::DiagnosticsService;
pub use discovery::DiscoveryService;
#[cfg(feature = "desktop")]
pub use export::ExportService;
pub use follow::FollowService;
#[cfg(feature = "desktop")]
pub use library::LibraryService;
pub use media_controls::MediaControlsService;
pub use playlist::PlaylistService;
pub use settings::SettingsService;
pub use tag::TagService;
